### ISSUE TITLE
Todo tasks

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/rhte_lab_2019#5]
## Todo taks

Team help !!
(only check something when it's done)

- [x] **Chris** - Deploy new version of generator
- [x] **Auri** - Generate Hal CLI commands as markdown files. See what odo [did](https://github.com/openshift/odo/blob/master/Makefile#L86-L92)
- [x] **Auri** - Play with hal tool, test/validate the [scenario](https://github.com/halkyonio/rhte_lab_2019/blob/master/scenario.md)
- [x] **Chris** - Improve hal from test performed at previous step
- [x] Fix kubedb issues about [webhook](https://github.com/kubedb/project/issues/639) and [authorization](https://github.com/kubedb/project/issues/634)
- [x] **Charles** - Write Lab step by step instructions - see #3 and template [example](https://github.com/redhat-gpte-devopsautomation/rhte2019_multi_cloud/blob/master/labguide/A0007%20Multi-Cloud%20OpenShift.adoc)
- [x] **Ioannis** - Create a github org and repo 'user1'......'user n` to let the students to use `deploymentmode = build = git` with the lab created using `hal`
- [x] **Auri** -add non-interactive version of the command
- [x] **Auri/Gytis** -Recording the scenario play with `asciinema`.

@aureamunoz @geoand @gytis @metacosm @iocanel 

RHTE OCP4 Cluster created this morning. Here are the infos to access/use it. It has been provisioned with Tekton 0.5.2, kubedb 0.12 and halkyon v0.1.4

To check if the cluster has bee created correctly (= status COMPLETED), use this link : https://spp.opentlc.com/service/explorer

To get the info about the cluster created and how to access it, use this url
https://www.opentlc.com/gg/gg.cgi?profile=generic_tester&operation=showguid&guid=416e&labcode=A2026&email=cmoulliard@redhat.com

The following URLs and information will be used in your lab environment. Please only access these links when the lab instructions specify to do so:

- Openshift Master Console: http://console-openshift-console.apps.cluster-416e.416e.sandbox352.opentlc.com
- Openshift API for command line 'oc' client: https://api.cluster-416e.416e.sandbox352.opentlc.com:6443
- User:  **opentlc-mgr** => has cluster admin role
  Password:  **r3dh4t1!**

**REMARK**: Student will access the platform using user --> `user1` and then this is the user to be used to make the tests !!!

**TIP**: You can log easily to the cluster using these commands
```
USER=opentlc-mgr
PASSWORD=r3dh4t1!
oc login -u $USER -p $PASSWORD https://api.cluster-416e.416e.sandbox352.opentlc.com:6443

OR

USER=user1
PASSWORD=r3dh4t1!
oc login -u $USER -p $PASSWORD https://api.cluster-416e.416e.sandbox352.opentlc.com:6443
```

![Screenshot 2019-09-05 10 09 17](https://user-images.githubusercontent.com/463790/64323774-687c6300-cfc5-11e9-9e0c-bfdbc8c2fc84.png)

**Comment by aureamunoz** [comment]
Generate Hal CLI commands as markdown files. See what odo did --> auri

**Comment by metacosm** [comment]
I'm going to create a document with the scenario using `hal`. In my mind, testing the scenario is the priority so that I can fix any bugs that you may found.

**Comment by iocanel** [comment]
I'll create the github org and repos.

**Comment by cmoulliard** [comment]
> I'll create the github org and repos

Great. As the lab will be played in Europe and US, we should find a way to use the org for EMEA or USA ... @iocanel

**Comment by iocanel** [comment]
I will also have a look that the kubedb issues and see if I can work something out.
Note, I am a complete kubedb noob, so I can't promise success.

**Comment by geoand** [comment]
I can (probably come Monday) look at validating the scenario and perhaps (with someone's input who knows more about RHTE) write the scenario

**Comment by iocanel** [comment]
> > I'll create the github org and repos
> 
> Great. As the lab will be played in Europe and US, we should find a way to use the org for EMEA or USA ... @iocanel

We'll just create two orgs, one for each. any preferences around names?

**Comment by cmoulliard** [comment]
> I'll create the github org and repos.

What is the name of the org ? @iocanel

**Comment by iocanel** [comment]
> > I'll create the github org and repos.
> 
> What is the name of the org ? @iocanel

Its `rhte-us` and `rhte-eu`.

**Comment by cmoulliard** [comment]
Asciinema scenario proposition. WDYT : @aureamunoz @gytis @metacosm 

```
oc login --token=FHCHfT3paTXJieBwV5YNCSjFWWN4LBknyhm7DjPmvdg --server=https://api.cluster-416e.416e.sandbox352.opentlc.com:6443
oc new-project cool-demo

mkdir rhtelab && cd rhtelab
hal component spring-boot \
   -i fruit-client-sb \
   -g me.fruitsand \
   -p me.fruitsand.demo \
   -s 2.1.6.RELEASE \
   -t client \
   -v 1.0.0-SNAPSHOT \
   --supported=false  \
  fruit-client-sb

hal component spring-boot \
   -i fruit-backend-sb \
   -g me.fruitsand \
   -p me.fruitsand.demo \
   -s 2.1.6.RELEASE \
   -t crud \
   -v 1.0.0-SNAPSHOT \
   --supported=false  \
  fruit-backend-sb

mvn clean package -Pkubernetes

hal component push -c fruit-client-sb,fruit-backend-sb
'fruit-client-sb' component was not found, initializing it
 ✓  Waiting for component fruit-client-sb to be ready…
 ✓  Uploading /Users/dabou/Temp/rhtelab/fruit-client-sb/target/fruit-client-sb-1.0.0-SNAPSHOT.jar
'fruit-backend-sb' component was not found, initializing it
 ✓  Waiting for component fruit-backend-sb to be ready…
 ✓  Uploading /Users/dabou/Temp/rhtelab/fruit-backend-sb/target/fruit-backend-sb-1.0.0-SNAPSHOT.jar


hal capability
? Category database
? Type postgres
? Version 10
? Change default name postgres-db
? Enter a value for string property DB_NAME: sample-db
? Enter a value for string property DB_PASSWORD: admin
? Enter a value for string property DB_USER: admin
 ✓  Created capability postgres-db


hal link
? Target component: fruit-backend-sb
? Use Secret Yes
? Secret postgres-db-config
? Change default name backend-to-db
 ✓  Created link backend-to-db


hal link
? Target component: fruit-client-sb
? Use Secret No
? Env variable in the 'name=value' format, press enter when done KUBERNETES_ENDPOINT_FRUIT=http://fruit-backend-sb:8080/api/fruits
Set env variable: KUBERNETES_ENDPOINT_FRUIT=http://fruit-backend-sb:8080/api/fruits
? Env variable in the 'name=value' format, press enter when done 
? Change default name client-to-backend
 ✓  Created link client-to-backend


open "http://$(oc get routes/fruit-backend-sb --template={{.spec.host}})"
FRONTEND_URL=$(oc get routes/fruit-client-sb --template={{.spec.host}})
curl "http://${FRONTEND_URL}/api/client"
```

**Comment by aureamunoz** [comment]
Hi, it's more or less what I had as well. We don't show the git repo part, right?
